name: PHP Linting
on: pull_request
jobs:
    phplint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            
            -   name: "laravel-pint"
                uses: aglipanci/laravel-pint-action@1.0.0
                with:
                    verboseMode: true
                    configPath: "pint.json"
                    
            -   name: Commit changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: Styles & Fix
